name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
permissions: write-all
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23.4"]
        go-arch: ["amd64", "arm64"]
        go-os: ["linux"]
        binary-name: ["trading212_exporter"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate build
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.go-os }}
          goarch: ${{ matrix.go-arch }}
          goversion: ${{ matrix.go-version }}
          build_command: "make build"
          binary_name: ${{ matrix.binary-name }}
          compress_assets: false
          release_tag: ${{ github.ref_name }}
          retry: 10
          overwrite: true
